# Generated by Django 5.2.1 on 2025-05-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category'),
            preserve_default='True',
        ),
    ]
